### PR TITLE
adds option to externally define build, module and src directories

### PR DESCRIPTION
**Pull request by wdavey**

### CODE REVIEW

**Comment by dgrimreaper** [comment]
oh yes please.  I'd love for this to be done for most of the variables that are hard cleared or hard coded at the start of the script

**Comment by marcodelapierre** [comment]
Guys, I want to review, and discuss, this one carefully.
Give me some time though, I am overwhelmed these days.

Note it can already be done, see comment below

**Comment by marcodelapierre** [comment]
by design, right now, you can edit those in 2 ways

1) through maali module definition, or shell variable :
re-define MAALI_ROOT_DEFAULT, MAALI_ROOT_GROUP, MAALI_ROOT_WORKST, or MAALI_ROOT_SYSTEM , see lines 69 and following; these are then used to define MAALI_ROOT , which in turn is used for MAALI_BUILD_DIR and others

2) through a config file, redefine MAALI_ROOT , which in turn is used for MAALI_BUILD_DIR and others

would one of these options suit you guys? these would work in the hypothesis that you're happy with MAALI_BUILD_DIR, MAALI_MODULE_DIR and MAALI_SRC being under the same parent dir (MAALI_ROOT_DIR) (edited)

**Comment by wdavey** [comment]
Yes but if I want my build directory to be someone completely different to that of where the modules and applications go, you can't do that as it's hardcoded to use MAALI_ROOT/*.

Ideally we should be building the software on the local fs rather than on /pawsey, so for my use case I have MAALI_BUILD_DIR set to /tmp/build in the .config file.

**Review by marcodelapierre — APPROVED** [review]
good to go, thanks for the patience William!

**Comment by marcodelapierre** [comment]
@wdavey , let me know how urgent this is, I can deploy a new maali version when needed

**Pull request merged**
