### PR TITLE
Update to UI and git src functionality

### PR DESCRIPTION
**Pull request by pelahi**
The code has been updated to provide a more informative usage statement and allow for more functionality in where cygnet files are located and where the install will occur. For git source, the cygnet file must contain an extra parameter `MAALI_GIT_SRC=1`. I am still deciding where documentation about this extra variable should be located. Further tests must be run to see if resulting module file also contains the extra information regarding the source and build date.

### CODE REVIEW

**Comment by chrisbuwahpc** [comment]
Hi Maybe trying setting it in a flag for the command line.  Otherwise it will require updating a bunch of cygnet files.

**Comment by marcodelapierre** [comment]
@pelahi , considering the size of the mods, 
can you push your branch as a side branch of this repo, with a dedicated name?

just to make it easier in case I need to do small makeups.
so feel free to close this PR and open one from the new maali branch.


I will add a second reviewer as well and try to have it sorted sooner rather than later, as I saw the HDF5 dependency.

**Comment by pelahi** [comment]
This pull request now has the requested command line flag for git source calls and also more descriptive UI (as seen in the attached text file). Critically, the code leaves module installs unchanged and just adds extra functionality. For instance, if a cygnet file makes use of the `MAALI_TOOL_BUILD_OPTIONS_SUFFIX` to indicate different builds, module files will have this name appended on the end. 

[maali_ui.txt](https://github.com/PawseySC/maali/files/5054834/maali_ui.txt)

**Comment by pelahi** [comment]
Currently, there is the unresolved issue that the whatis is not nicely formatted since it now contains extra build info. Example 

```
$ module whatis hdf5/1.12.0-c++-noparallel-api-v112

hdf5/1.12.0-c++-noparallel-api-v112                                     : HDF5 is a data model, library, and file format for storing and managing data.
It supports an unlimited variety of datatypes, and is designed for flexible and
efficient I/O and for high volume and complex data. HDF5 is portable and is
extensible, allowing applications to evolve in their use of HDF5. The HDF5
Technology suite includes tools and applications for managing, manipulating,
viewing, and analyzing data in the HDF5 format.

For further information see https://www.hdfgroup.org/hdf5/<Local Version: 1.12.0> <Config Options: > <Build Date: Mon Aug 10 17:10:41 AWST 2020> <Local Version: 1.12.0> <Config Options: > <Build D
ate: Mon Aug 10 17:16:07 AWST 2020> <Local Version: 1.12.0> <Config Options: > <Build Date: Mon Aug 10 17:20:31 AWST 2020> <Local Version: 1.12.0> <Config Options: > <Build Date: Mon Aug 10 17:25:
57 AWST 2020> 
hdf5/1.12.0-c++-noparallel-api-v112                                     : Compiled with gcc/8.3.0
hdf5/1.12.0-c++-noparallel-api-v112                                     : Compiled with intel/19.0.5
hdf5/1.12.0-c++-noparallel-api-v112                                     : Compiled for broadwell
hdf5/1.12.0-c++-noparallel-api-v112                                     : Compiled for cascadelake

```

**Comment by marcodelapierre** [comment]
@pascal going to merge this straight away, and then do the actual review work in the following PR

**Pull request merged**
